spring:
  application:
    name: Financial-al
  profiles:
    active: dev
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        enabled: true
        options:
          model: gpt-4
          temperature: 0.7

cloudinary:
  name: "dzmzrbuta"
  api:
    key: ${CLOUDINARY_KEY}
    secret: ${CLOUDINARY_SECRET}

server:
  port: 8090
  error:
    include-message: always
