#spring.application.name=Financial.land
#server.port=8090
#spring.datasource.url=${POSTGRES_URL}
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.maximum-pool-size=10

spring:
  application:
    name: Financial-al
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            timeout: 5000
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        enabled: true
        options:
          model: gpt-4
          temperature: 0.7

server:
  port: 8090
  error:
    include-message: always

frontend:
  url: ${FRONTEND_URL}